### PR TITLE
fix headers

### PR DESCRIPTION
**Pull request by little-dude**

### CODE REVIEW

**Comment by little-dude** [comment]
@t00f I think the test is wrong here: we do have an `externalID` attribute, don't we ?

**Comment by t00f** [comment]
Yes, we do have an `externalID`

**Comment by t00f** [comment]
Your PR looks good to me. You should launch unit tests locally to ensure everything is working.

**Comment by little-dude** [comment]
@t00f this is ready, once you reviewed the commit that fixes the tests.
I'll make a release when this is merged.

**Comment by t00f** [comment]
Looks good ! Thanks @little-dude

**Pull request merged**
