### PR TITLE
Fix for issue with VRS fetching

### LINKED ISSUE #1: Fetching VRSs causes error
If you request the VRSs from a VSC. It will return an error: 400 Bad request. 

It is using the wrong URL to fetch the VRSs (.../vscs/ID/vrs instead of .../vscs/ID/vrss)

Code example:

```
import logging
from vspk.vsdk import v3_2 as vsdk
from vspk.vsdk.v3_2.utils import set_log_level

log_level = logging.INFO
set_log_level(log_level)
nc = vsdk.NUVSDSession(username="csproot", password="PASSWORD", enterprise="csp", api_url="https://VSD-IP:8443")
nc.start()
nc.user.vsps.get()[0].vscs.get()[0].vrss.get()
```

Return:

```
Bambou Sending >>>>>>
GET https://10.167.43.64/nuage/api/v3_2/vscs/589de448-d016-4cd3-91d9-3f8d258e93e3/vrs with following data:
null
Bambou <<<<< Response [400] for
GET https://10.167.43.64/nuage/api/v3_2/vscs/589de448-d016-4cd3-91d9-3f8d258e93e3/vrs
null
---------------------------------------------------------------------------
BambouHTTPError                           Traceback (most recent call last)
<ipython-input-8-9570ff7866a4> in <module>()
----> 1 nc.user.vsps.get()[0].vscs.get()[0].vrss.get()

/usr/lib/python2.7/site-packages/bambou/nurest_fetcher.pyc in get(self, filter, order_by, group_by, page, page_size, commit, async, callback)
    351                 [<NUChildren at xxx>, <NUChildren at yyyy>, <NUChildren at zzz>]
    352         """
--> 353         return self.fetch(filter=filter, order_by=order_by, group_by=group_by, page=page, page_size=page_size, commit=False)[2]
    354
    355     def get_first(self, filter=None, order_by=None, group_by=[], page=None, page_size=None, commit=True, async=False, callback=None):

/usr/lib/python2.7/site-packages/bambou/nurest_fetcher.pyc in fetch(self, filter, order_by, group_by, page, page_size, commit, async, callback)
    271
    272         connection = self.parent_object.send_request(request=request, user_info={'commit': commit})
--> 273         return self._did_fetch(connection=connection)
    274
    275     def _did_fetch(self, connection):

/usr/lib/python2.7/site-packages/bambou/nurest_fetcher.pyc in _did_fetch(self, connection)
    281
    282         if connection.response.status_code >= 400 and BambouConfig._should_raise_bambou_http_error:
--> 283             raise BambouHTTPError(connection=connection)
    284
    285         if response.status_code != 200:

BambouHTTPError: [HTTP 400(Bad Request)] {}
```

### PR DESCRIPTION
**Pull request by pdellaert**
Resolves #1 : This pull request should fix the fetching of the VRSs. In the current version, the wrong url is called: .../vscs/ID/vrs . This should be .../vscs/ID/vrss

### CODE REVIEW

**Comment by primalmotion** [comment]
Hi,

Thanks for the PR, but this is not the correct way to do. It will work until we release a patch, in `vspk` but this is a bug in auto generation.

A better approach for fixing it right now is to modify the `nuvrs.py` file and implement the method

``` python
    @classmethod
    def is_resource_name_fixed(cls):
        return True
```

This will avoid the auto pluralization of the resource name

`Bambou` should not have to know related to `vsd` and its object model.

Thanks

**Comment by pdellaert** [comment]
I was wondering if it was the right way or not, so sure :). I understand the reasoning why bambou should not know about the VSD structure.

However, your solution won't work. The problem is that `vrs` is not being pluralised, while it has to be pluralised. Your solution will just force it to never being pluralised, which is the opposite of what is required.

**Comment by pdellaert** [comment]
It seems like you have three options here:
- Use this work around
- Change https://github.com/nuagenetworks/vspk/blob/master/vsdk/v3_2/nuvrs.py  (and the v3_1, v3_0 ones) and add `__rest_name__ = u"vrss"`
- Update/Fix auto generate (i have no idea where to do that).

**Comment by primalmotion** [comment]
you are correct, I misread the error. "vrss" didn't sound very obvious at a glance :)

There is a better way then, I'll comment in the PR in vspk repo. thanks

**Pull request closed without merging**
